### ISSUE TITLE
[QUESTION] How is envycontrol different from supergfxctl of asusctl?

### ISSUE THREAD

**Issue by HarshalRathore** [bayasdev/envycontrol#104]
## Questions
**Some example questions of a new user being conflicted between choosing envycontrol & supergfxctl for ASUS Machines**
- How envycontrol is different from supergfxctl of asusctl in terms of feature and efficiency?
- Does envycontrol provides better control on power than supergfxctl? 
- Why does changing the modes from integrated->Hybrid or vice-versa requires system reboot in envycontrol but supergfxctl just logs out from the desktop session for changing the gpu mode? 
- Is this the only difference they have and are same in rest?

**Comment by bayasdev** [comment]
> - Why does changing the modes from integrated->Hybrid or vice-versa requires system reboot in envycontrol but supergfxctl just logs out from the desktop session for changing the gpu mode? 

We need the Nvidia GPU PCI bus ID to build the Xorg config which isn't possible on integrated mode.

Envycontrol was built as a portable tool for dealing with Optimus shenanigans on my old Predator G3-571, but I recommend you giving Asusctl a try since it talks directly with the hardware through the asus-linux kernel driver ;)
