### ISSUE TITLE
Doesn't work on Debian 11

### ISSUE THREAD

**Issue by tazihad** [bayasdev/envycontrol#59]
I see black screen when reboot. Completely turned off screen. 
fortunately I recovered from recovery screen. please mention Debian 11 not supported in wiki. So, other people won't have to face same issue.

**Comment by porschemad911** [comment]
I am currently running Debian 11 on a Haswell CPU / Maxwell GPU Optimus machine using the Nvidia binary drivers plus prime render offload and am thinking of trying envycontrol. However your comment has me hesitating a bit!

Some more info would be needed to aid debugging however:
1. Can you describe how you installed this on Debian 11?
2. Which mode did you enable prior to rebooting (integrated / hybrid / nvidia)?
3. Were you using an external monitor or internal laptop display?
4. What model of laptop are you using (trying to determine how the display outputs are wired)?

**Comment by geminis3** [comment]
@porschemad911 Debian 11 base it's relatively new, I remember testing envycontrol on Ubuntu 20.04 with 470 drivers.

Hybrid mode / render offloading should work since 435.17.

@zihadio what's your iGPU/dGPU combination as well as Nvidia driver version and lspci output?

Thanks

**Comment by porschemad911** [comment]
This evening I tried envycontrol out on my Metabox P650SE with Intel 4th gen CPU and GTX 970M, running Debian Bullseye (11) and Nvidia 515.65 drivers installed from the Nvidia repo at https://developer.download.nvidia.com/compute/cuda/repos/debian11/x86_64/

I'm using an xdm / lxqt setup and the integrated and hybrid modes worked flawlessly for me. I got an error attempting to switch into the nvidia mode because xdm is not a supported display manager.

This laptop conveniently has an indicator light to show whether the Nvidia GPU is powered on. In integrated mode the indicator light is off, nvidia-smi, nvidia-settings and nvtop report no Nvidia GPU detected, lspci does not pick up the Nvidia GPU and power consumption indicates 13 - 14W under light loads. In hybrid mode the indicator light is on, nvidia-smi, nvidia-settings, nvtop and lspci show the Nvidia GPU with a reported 5W power consumption when not in use, power consumption indicates around 22W under light loads on the Intel GPU and I am able to use prime render offload to launch games etc on the Nvidia GPU.

@geminis3 Kudos to you, this util is working really nicely for me! t would be a bonus if xdm support could be added, although nvidia mode is not a high priority for me and I double many people are using xdm these days anyway.

**Comment by zihadio** [comment]
> I am currently running Debian 11 on a Haswell CPU / Maxwell GPU Optimus laptop using the Nvidia binary drivers plus prime render offload and am thinking of trying envycontrol. However your comment has me hesitating a bit!
> 
> Some more info would be needed to aid debugging however:
> 
>     1. Can you describe how you installed this on Debian 11?
> 
>     2. Which mode did you enable prior to rebooting (integrated / hybrid / nvidia)?
> 
>     3. Were you using an external monitor or internal laptop display?
> 
>     4. What model of laptop are you using (trying to determine how the display outputs are wired)?

1. installed using [this](https://github.com/geminis3/envycontrol#other-distros) method. 
2. I tried all of them from tty.
3. I have external monitor. But I also tried without ext monitor. 
4. it is Asus x550jk. laptop display is directly connected to integrated gpu.

**Comment by zihadio** [comment]
> 

```
❯ lspci
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor DRAM Controller (rev 06)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor PCI Express x16 Controller (rev 06)
00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
00:03.0 Audio device: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller (rev 06)
00:14.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB xHCI (rev 05)
00:16.0 Communication controller: Intel Corporation 8 Series/C220 Series Chipset Family MEI Controller #1 (rev 04)
00:1b.0 Audio device: Intel Corporation 8 Series/C220 Series Chipset High Definition Audio Controller (rev 05)
00:1c.0 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #1 (rev d5)
00:1c.2 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #3 (rev d5)
00:1c.3 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #4 (rev d5)
00:1f.0 ISA bridge: Intel Corporation HM86 Express LPC Controller (rev 05)
00:1f.2 SATA controller: Intel Corporation 8 Series/C220 Series Chipset Family 6-port SATA Controller 1 [AHCI mode] (rev 05)
00:1f.3 SMBus: Intel Corporation 8 Series/C220 Series Chipset Family SMBus Controller (rev 05)
01:00.0 3D controller: NVIDIA Corporation GM107M [GeForce GTX 850M] (rev a2)
03:00.0 Network controller: Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter (rev 01)
04:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTL8411B PCI Express Card Reader (rev 01)
04:00.1 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 12)

```
I am also using Fedora 36 kinoite. Not sure if it will work.

**Comment by geminis3** [comment]
@zihadio what's your Nvidia driver version?

**Comment by zihadio** [comment]
I am not using Debian now. Using Fedora 36. nvidia Driver Version: 515.65.01

**Comment by bayasdev** [comment]
@tazihad are you still experiencing this?
